/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useContext, useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";

import Enigme from "../Enigme";
import useInteractiveObject from "../../hooks/useInteractiveObject";
import { SocketContext } from "../../context/socket";

export default function Room001(props) {
	const socket = useContext(SocketContext);

	useEffect(() => {
		socket.emit("ready");
	});

	const { nodes, materials } = useGLTF("/models/Demo_Room-002.glb");

	const mesh = useRef();

	const MarmiteInt = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Marmite"
				castShadow
				receiveShadow
				geometry={nodes.Marmite.geometry}
				material={materials["Metal.001"]}
				position={[0, 0.1, 0]}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0x00ff00} />}
				{clicked && (
					<Enigme
						titre="Titre de l enigme"
						textEnigme="Contenue de l enigme"
						indiceEnigme="0<x<2"
						reponseEnigme={1}
					/>
				)}
			</mesh>
		);
	};

	const FeuilleInt = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Feuille005"
				castShadow
				receiveShadow
				geometry={nodes.Feuille005.geometry}
				material={nodes.Feuille005.material}
				position={[0.68, 0.312, 1.228]}
				rotation={[Math.PI / 2, 0, 0.436]}
				scale={0.08}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0x00ff00} />}
				{clicked && (
					<Enigme
						titre="Recette de potion de souris"
						textEnigme="C la seule chose qui est compréhensible parmit le tas de feuille"
						indiceEnigme="Regarder bien autour de vous"
					/>
				)}
			</mesh>
		);
	};

	return (
		<group {...props} dispose={null}>
			<group name="Scene">
				<group name="Room">
					<mesh
						name="Cylinder"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder.geometry}
						material={materials.Room}
					/>
					<mesh
						name="Cylinder_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder_1.geometry}
						material={materials.Floor}
					/>
				</group>
				<group
					name="Cuve001"
					position={[0, 1.8, 0]}
					rotation={[0, 0, -Math.PI / 2]}
				>
					<mesh
						name="Sphere"
						castShadow
						receiveShadow
						geometry={nodes.Sphere.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Sphere_1"
						castShadow
						receiveShadow
						geometry={nodes.Sphere_1.geometry}
						material={materials["Metal_Vers.002"]}
					/>
					<mesh
						name="Sphere_2"
						castShadow
						receiveShadow
						geometry={nodes.Sphere_2.geometry}
						material={materials.Liquide}
					/>
				</group>
				<group name="Verseur" position={[0, 1.19, 0]}>
					<mesh
						name="Sphere001"
						castShadow
						receiveShadow
						geometry={nodes.Sphere001.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Sphere001_1"
						castShadow
						receiveShadow
						geometry={nodes.Sphere001_1.geometry}
						material={materials["Metal_Vers.002"]}
					/>
				</group>
				<MarmiteInt />
				<group
					name="Cylinder002"
					position={[0, 1.39, 0]}
					scale={[0.12, 0.03, 0.12]}
				>
					<mesh
						name="Cylinder003"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder003.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Cylinder003_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder003_1.geometry}
						material={materials["Metal_Vers.002"]}
					/>
				</group>
				<mesh
					name="Pipe004"
					castShadow
					receiveShadow
					geometry={nodes.Pipe004.geometry}
					material={materials["Metal_Vers.002"]}
					position={[0.25, 2.27, 0]}
					scale={[0.027, 0.2, 0.027]}
				/>
				<group name="Cylinder008" position={[0, 2.5, 0]}>
					<mesh
						name="Cylinder009"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder009.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Cylinder009_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder009_1.geometry}
						material={materials["Metal_Vers.002"]}
					/>
				</group>
				<group name="Chaud" position={[-0.7, 0.4, -0.6]}>
					<mesh
						name="Cylinder035_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder035_1.geometry}
						material={materials["Metal_Vers.002"]}
					/>
					<mesh
						name="Cylinder035_2"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder035_2.geometry}
						material={materials["Metal.001"]}
					/>
				</group>
				<mesh
					name="Armoir"
					castShadow
					receiveShadow
					geometry={nodes.Armoir.geometry}
					material={materials["Wood.001"]}
					position={[1.3, 0.7, -1.85]}
				/>
				<group
					name="Rangement"
					position={[0.72, 1.28, -1.83]}
					scale={[0.08, 0.08, 0.14]}
				>
					<mesh
						name="Cube012"
						castShadow
						receiveShadow
						geometry={nodes.Cube012.geometry}
						material={materials["Wood.002"]}
					/>
					<mesh
						name="Cube012_1"
						castShadow
						receiveShadow
						geometry={nodes.Cube012_1.geometry}
						material={materials["Metal_Vers.002"]}
					/>
				</group>
				<mesh
					name="Poigne"
					castShadow
					receiveShadow
					geometry={nodes.Poigne.geometry}
					material={materials["Metal_Vers.002"]}
					position={[0.72, 1.28, -1.66]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.02}
				/>
				<mesh
					name="Echelle001"
					castShadow
					receiveShadow
					geometry={nodes.Echelle001.geometry}
					material={materials["Wood.002"]}
					position={[0.462, 0.971, -1.829]}
					rotation={[0, 0, -0.262]}
				/>
				<group name="Cuve003" position={[-1.7, 1.3, 0.6]}>
					<mesh
						name="Cylinder037_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder037_1.geometry}
						material={materials["Glass.002"]}
					/>
					<mesh
						name="Cylinder037_2"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder037_2.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Cylinder037_3"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder037_3.geometry}
						material={materials["Metal_Vers.002"]}
					/>
				</group>
				<mesh
					name="Support_Cuve"
					castShadow
					receiveShadow
					geometry={nodes.Support_Cuve.geometry}
					material={materials["Metal.001"]}
					position={[-1.7, 0.2, 0.6]}
					scale={[0.9, 0.2, 0.9]}
				/>
				<group name="Cylinder032" position={[-1.7, 1.3, 0.6]} scale={0.9}>
					<mesh
						name="Cylinder015_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder015_1.geometry}
						material={materials["Metal_Vers.002"]}
					/>
					<mesh
						name="Cylinder015_2"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder015_2.geometry}
						material={materials["Metal.001"]}
					/>
				</group>
				<group
					name="Cuve002"
					position={[-1.3, 0.54, -1.4]}
					rotation={[0, -Math.PI / 6, 0]}
					scale={0.9}
				>
					<mesh
						name="Cylinder038_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder038_1.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Cylinder038_2"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder038_2.geometry}
						material={materials.Liquide}
					/>
				</group>
				<group name="Hote" position={[-1.3, 2.7, -1.4]} scale={0.3}>
					<mesh
						name="Cylinder001"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder001.geometry}
						material={materials["Metal_Vers.002"]}
					/>
					<mesh
						name="Cylinder001_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder001_1.geometry}
						material={materials["Metal.001"]}
					/>
				</group>
				<mesh
					name="Pipe002"
					castShadow
					receiveShadow
					geometry={nodes.Pipe002.geometry}
					material={materials["Glass.001"]}
				/>
				<mesh
					name="Pipe003"
					castShadow
					receiveShadow
					geometry={nodes.Pipe003.geometry}
					material={materials["Glass.001"]}
					position={[-0.004, 0, -0.001]}
				/>
				<mesh
					name="Pipe001"
					castShadow
					receiveShadow
					geometry={nodes.Pipe001.geometry}
					material={materials["Glass.001"]}
				/>
				<mesh
					name="Porte_Potion001"
					castShadow
					receiveShadow
					geometry={nodes.Porte_Potion001.geometry}
					material={materials["Metal.001"]}
					position={[-0.7, 1.447, -0.6]}
					rotation={[Math.PI, -1.396, Math.PI]}
					scale={[0.191, 0.152, 0.191]}
				/>
				<mesh
					name="Potion010"
					castShadow
					receiveShadow
					geometry={nodes.Potion010.geometry}
					material={materials["Glass.003"]}
					position={[-0.7, 1.51, -0.6]}
					rotation={[0.436, 0, 0]}
					scale={0.252}
				/>
				<mesh
					name="Echelle002"
					castShadow
					receiveShadow
					geometry={nodes.Echelle002.geometry}
					material={materials["Wood.002"]}
					position={[-0.388, 0.971, -0.849]}
					rotation={[-Math.PI, -0.698, 2.88]}
				/>
				<mesh
					name="Bouchon"
					castShadow
					receiveShadow
					geometry={nodes.Bouchon.geometry}
					material={materials["Wood.002"]}
					position={[-0.7, 1.51, -0.6]}
					rotation={[0.436, 0, 0]}
					scale={0.252}
				/>
				<mesh
					name="Sphere011"
					castShadow
					receiveShadow
					geometry={nodes.Sphere011.geometry}
					material={materials["Liquide.001"]}
					position={[-0.7, 1.51, -0.6]}
					scale={0.227}
				/>
				<mesh
					name="Flame"
					castShadow
					receiveShadow
					geometry={nodes.Flame.geometry}
					material={materials.Flame}
					position={[-0.56, 1.23, -0.6]}
					rotation={[0, 0, -0.665]}
					scale={0.028}
				/>
				<mesh
					name="Mball011"
					castShadow
					receiveShadow
					geometry={nodes.Mball011.geometry}
					material={materials.Liquide}
					position={[-1.3, 1, -1.46]}
				/>
				<mesh
					name="Chaine"
					castShadow
					receiveShadow
					geometry={nodes.Chaine.geometry}
					material={materials["Metal.001"]}
					position={[0, 1.33, 0.5]}
				/>
				<mesh
					name="Plane"
					castShadow
					receiveShadow
					geometry={nodes.Plane.geometry}
					material={materials.Logo}
					position={[0, 3, 0]}
					scale={0.3}
				/>
				<mesh
					name="Cube"
					castShadow
					receiveShadow
					geometry={nodes.Cube.geometry}
					material={materials["Metal_Vers.002"]}
					position={[1.39, 0.6, 1.96]}
					rotation={[0, -1.571, 0]}
				/>
				<mesh
					name="Pipe005"
					castShadow
					receiveShadow
					geometry={nodes.Pipe005.geometry}
					material={materials["Glass.001"]}
				/>
				<mesh
					name="Masque"
					castShadow
					receiveShadow
					geometry={nodes.Masque.geometry}
					material={materials.Crane}
					position={[0.416, 0.913, 1.57]}
					rotation={[-2.281, 0.713, 2.491]}
					scale={0.76}
				/>
				<mesh
					name="Deco_Bureau"
					castShadow
					receiveShadow
					geometry={nodes.Deco_Bureau.geometry}
					material={materials["Wood.001"]}
					position={[0.5, 1.04, 1.7]}
					rotation={[0.593, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Deco_Bureau001"
					castShadow
					receiveShadow
					geometry={nodes.Deco_Bureau001.geometry}
					material={materials["Wood.001"]}
					position={[0.49, 1.14, 1.7]}
					rotation={[0.593, -Math.PI / 2, 0]}
				/>
				<FeuilleInt />
				<mesh
					name="Feuille004"
					castShadow
					receiveShadow
					geometry={nodes.Feuille004.geometry}
					material={nodes.Feuille004.material}
					position={[0.75, 0.312, 1.318]}
					rotation={[Math.PI / 2, 0, -0.175]}
					scale={0.08}
				/>
				<mesh
					name="Feuille006"
					castShadow
					receiveShadow
					geometry={nodes.Feuille006.geometry}
					material={nodes.Feuille006.material}
					position={[0.79, 0.312, 1.118]}
					rotation={[Math.PI / 2, 0, 1.222]}
					scale={0.08}
				/>
				<mesh
					name="Feuille003"
					castShadow
					receiveShadow
					geometry={nodes.Feuille003.geometry}
					material={nodes.Feuille003.material}
					position={[0.72, 0.312, 1.398]}
					rotation={[Math.PI / 2, 0, Math.PI / 9]}
					scale={0.08}
				/>
				<mesh
					name="Feuille002"
					castShadow
					receiveShadow
					geometry={nodes.Feuille002.geometry}
					material={nodes.Feuille002.material}
					position={[0.68, 0.312, 1.508]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.08}
				/>
				<mesh
					name="Feuille001"
					castShadow
					receiveShadow
					geometry={nodes.Feuille001.geometry}
					material={nodes.Feuille001.material}
					position={[0.66, 0.313, 1.528]}
					rotation={[Math.PI / 2, 0, -0.087]}
					scale={0.08}
				/>
				<mesh
					name="Porte_Potion"
					castShadow
					receiveShadow
					geometry={nodes.Porte_Potion.geometry}
					material={materials["Metal.001"]}
					position={[0.27, 0.4, 1.04]}
					scale={0.042}
				/>
				<group
					name="Sablier"
					position={[0.4, 0.901, 1.431]}
					scale={[0.04, 0.03, 0.04]}
				>
					<mesh
						name="Cone"
						castShadow
						receiveShadow
						geometry={nodes.Cone.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cone_1"
						castShadow
						receiveShadow
						geometry={nodes.Cone_1.geometry}
						material={materials["Metal.001"]}
					/>
				</group>
				<mesh
					name="Bureau"
					castShadow
					receiveShadow
					geometry={nodes.Bureau.geometry}
					material={materials["Wood.001"]}
					position={[0.29, 0.5, 1.3]}
				/>
				<mesh
					name="Table"
					castShadow
					receiveShadow
					geometry={nodes.Table.geometry}
					material={materials["Wood.001"]}
					position={[0.7, 0.3, 1.3]}
				/>
				<mesh
					name="Chaise"
					castShadow
					receiveShadow
					geometry={nodes.Chaise.geometry}
					material={materials["Wood.001"]}
					position={[1.01, 0.19, 1.31]}
				/>
				<mesh
					name="Support_Tube"
					castShadow
					receiveShadow
					geometry={nodes.Support_Tube.geometry}
					material={materials["Wood.002"]}
					position={[0.32, 0.357, 1.288]}
				/>
				<mesh
					name="Coffre"
					castShadow
					receiveShadow
					geometry={nodes.Coffre.geometry}
					material={nodes.Coffre.material}
					position={[0.41, 0.915, 1.04]}
				/>
				<mesh
					name="ancre"
					castShadow
					receiveShadow
					geometry={nodes.ancre.geometry}
					material={materials["Metal.001"]}
					position={[0.67, 0.322, 1.099]}
				/>
				<group
					name="Plume"
					position={[0.67, 0.35, 1.082]}
					rotation={[-0.96, 0, 0]}
					scale={[0.002, 0.034, 0.002]}
				>
					<mesh
						name="Cylinder014"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder014.geometry}
						material={materials.Room}
					/>
					<mesh
						name="Cylinder014_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder014_1.geometry}
						material={materials.Crane}
					/>
				</group>
				<mesh
					name="Tube_Essai"
					castShadow
					receiveShadow
					geometry={nodes.Tube_Essai.geometry}
					material={materials["Glass.001"]}
					position={[0.32, 0.42, 1.34]}
				/>
				<group name="Potion002" position={[0.39, 0.355, 1.56]} scale={0.048}>
					<mesh
						name="Cylinder019"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder019.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder019_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder019_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<group name="Potion005" position={[0.388, 0.725, 1.17]} scale={1.1}>
					<mesh
						name="Cylinder022"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder022.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder022_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder022_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<mesh
					name="Potion006"
					castShadow
					receiveShadow
					geometry={nodes.Potion006.geometry}
					material={materials["Glass.001"]}
					position={[0.405, 0.733, 1.28]}
					scale={[1.13, 0.6, 1.13]}
				/>
				<group
					name="Potion007"
					position={[0.36, 0.72, 1.34]}
					scale={[0.044, 0.05, 0.044]}
				>
					<mesh
						name="Cylinder025"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder025.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder025_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder025_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<group name="Potion008" position={[0.41, 0.715, 1.441]} scale={0.045}>
					<mesh
						name="Cylinder026"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder026.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder026_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder026_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<group name="Potion009" position={[0.37, 0.706, 1.53]} scale={0.036}>
					<mesh
						name="Cylinder027"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder027.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder027_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder027_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<group name="Potion011" position={[0.42, 0.706, 1.6]} scale={0.036}>
					<mesh
						name="Cylinder028"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder028.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder028_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder028_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<mesh
					name="Sphere_Bureau"
					castShadow
					receiveShadow
					geometry={nodes.Sphere_Bureau.geometry}
					material={materials["Wood.002"]}
					position={[0.5, 1.16, 1.7]}
				/>
				<group
					name="Potion001"
					position={[0.27, 0.419, 1.04]}
					rotation={[-Math.PI, -1.257, 2.723]}
					scale={0.046}
				>
					<mesh
						name="Sphere004"
						castShadow
						receiveShadow
						geometry={nodes.Sphere004.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Sphere004_1"
						castShadow
						receiveShadow
						geometry={nodes.Sphere004_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<group name="Orbe" position={[0.41, 0.905, 1.26]}>
					<mesh
						name="Sphere005"
						castShadow
						receiveShadow
						geometry={nodes.Sphere005.geometry}
						material={materials.Crane}
					/>
					<mesh
						name="Sphere005_1"
						castShadow
						receiveShadow
						geometry={nodes.Sphere005_1.geometry}
						material={materials["Wood.002"]}
					/>
					<mesh
						name="Sphere005_2"
						castShadow
						receiveShadow
						geometry={nodes.Sphere005_2.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Sphere005_3"
						castShadow
						receiveShadow
						geometry={nodes.Sphere005_3.geometry}
						material={materials["Metal_Vers.002"]}
					/>
				</group>
				<mesh
					name="Support_Bureau"
					castShadow
					receiveShadow
					geometry={nodes.Support_Bureau.geometry}
					material={materials["Metal.001"]}
					position={[0.22, 0.62, 1.61]}
					scale={[1, 1, 0.549]}
				/>
				<mesh
					name="Support_Bureau001"
					castShadow
					receiveShadow
					geometry={nodes.Support_Bureau001.geometry}
					material={materials["Metal.001"]}
					position={[0.32, 0.962, 1.61]}
					scale={[1, 1, 0.549]}
				/>
				<mesh
					name="Livre001"
					castShadow
					receiveShadow
					geometry={nodes.Livre001.geometry}
					material={materials["Livre.004"]}
					position={[0.4, 1.062, 1.138]}
				/>
				<mesh
					name="Livre002"
					castShadow
					receiveShadow
					geometry={nodes.Livre002.geometry}
					material={materials["Livre.003"]}
					position={[0.4, 1.081, 1.017]}
				/>
				<mesh
					name="Livre003"
					castShadow
					receiveShadow
					geometry={nodes.Livre003.geometry}
					material={materials["Livre.001"]}
					position={[0.4, 1.078, 1.076]}
				/>
				<mesh
					name="Cube028"
					castShadow
					receiveShadow
					geometry={nodes.Cube028.geometry}
					material={materials["Livre.002"]}
					position={[0.4, 1.082, 1.599]}
				/>
				<mesh
					name="Cylinder033"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder033.geometry}
					material={materials["Liquide.001"]}
					position={[0.388, 0.724, 1.17]}
					scale={1.015}
				/>
				<group name="Potion004" position={[0.371, 0.725, 1.072]} scale={1.1}>
					<mesh
						name="Cylinder017"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder017.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder017_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder017_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<mesh
					name="Cylinder035"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder035.geometry}
					material={materials["Liquide.001"]}
					position={[0.371, 0.724, 1.072]}
					scale={1.015}
				/>
				<group name="Potion003" position={[0.407, 0.725, 0.99]} scale={1.1}>
					<mesh
						name="Cylinder029"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder029.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder029_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder029_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<mesh
					name="Cylinder037"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder037.geometry}
					material={materials["Liquide.001"]}
					position={[0.407, 0.724, 0.99]}
					scale={1.015}
				/>
				<mesh
					name="Cylinder015"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder015.geometry}
					material={materials.Liquide}
					position={[0.39, 0.355, 1.56]}
					scale={0.043}
				/>
				<mesh
					name="Cylinder016"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder016.geometry}
					material={materials["Liquide.001"]}
					position={[0.41, 0.715, 1.441]}
					scale={0.041}
				/>
				<mesh
					name="Cylinder038"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder038.geometry}
					material={materials["Liquide.001"]}
					position={[0.36, 0.72, 1.34]}
					scale={[0.04, 0.045, 0.04]}
				/>
				<mesh
					name="Cylinder039"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder039.geometry}
					material={materials["Liquide.001"]}
					position={[0.37, 0.706, 1.53]}
					scale={0.032}
				/>
				<mesh
					name="Cylinder040"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder040.geometry}
					material={materials["Liquide.001"]}
					position={[0.42, 0.706, 1.6]}
					scale={0.032}
				/>
				<mesh
					name="Cylinder041"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder041.geometry}
					material={materials["Liquide.001"]}
					position={[0.405, 0.723, 1.28]}
					scale={[1.084, 0.576, 1.084]}
				/>
				<mesh
					name="Sphere008"
					castShadow
					receiveShadow
					geometry={nodes.Sphere008.geometry}
					material={materials["Liquide.001"]}
					position={[0.27, 0.419, 1.04]}
					scale={0.04}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/models/Demo_Room-002.glb");
