/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from 'three';

export function Room001(props) {
  const mesh = useRef();
  const [hovered, setHovered] = useState(false);

  const handlePointerOver = () => {
    setHovered(true);
  };

  const handlePointerOut = () => {
    setHovered(false);
  };

  const { nodes, materials } = useGLTF("/models/Demo_Room-002.glb");
  
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.8, 0]} rotation={[0, 0, -Math.PI / 2]} scale={0.4}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_1.geometry}
          material={materials["Metal.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_2.geometry}
          material={materials["Metal_Vers.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere_3.geometry}
          material={materials.Liquide}
        />
      </group>
      <group position={[0, 1.19, 0]} scale={0.2}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_1.geometry}
          material={materials["Metal.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere001_2.geometry}
          material={materials["Metal_Vers.002"]}
        />
      </group>

      <mesh
        ref={mesh}
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["Metal.001"]}
        position={[0, 0.1, 0]}
        onPointerOver={handlePointerOver}
        onPointerOut={handlePointerOut}
      >
        {/* Change la couleur du matériau lorsqu'il est survolé */}
        {hovered && (
          <meshBasicMaterial color={0xffcc00} /> 
          // Ajuster la couleur ou utiliser un matériau différent ici
        )}
      </mesh>

      <group position={[0, 1.39, 0]} scale={[0.12, 0.03, 0.12]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_1.geometry}
          material={materials["Metal.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_2.geometry}
          material={materials["Metal_Vers.002"]}
        />
      </group>
      <group position={[0, 1.8, 0.4]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_1.geometry}
          material={materials["Metal_Vers.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_2.geometry}
          material={materials["Metal.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials["Metal_Vers.002"]}
        position={[0, 1.19, -0.22]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials["Metal_Vers.002"]}
        position={[0.04, 1.14, -0.2]}
        rotation={[-Math.PI / 2, 0, -0.237]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials["Metal_Vers.002"]}
        position={[-0.06, 1.23, -0.19]}
        rotation={[-Math.PI / 2, 0, 0.237]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials["Metal_Vers.002"]}
        position={[0.25, 2.27, 0]}
        scale={[0.027, 0.2, 0.027]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={materials["Metal.001"]}
        position={[0, 2.5, 0]}
      />
      <group position={[-0.7, 0.4, -0.6]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder035_1.geometry}
          material={materials["Metal_Vers.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder035_2.geometry}
          material={materials["Metal.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials["Wood.001"]}
        position={[1.3, 0.7, -1.85]}
      />
      <group position={[0.72, 1.28, -1.83]} scale={[0.08, 0.08, 0.14]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_1.geometry}
          material={materials["Wood.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_2.geometry}
          material={materials["Metal_Vers.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere006.geometry}
        material={materials["Metal_Vers.002"]}
        position={[0.72, 1.28, -1.66]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials["Wood.002"]}
        position={[0.462, 0.971, -1.829]}
        rotation={[0, 0, -0.262]}
      />
      <group position={[-1.7, 1.3, 0.6]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder037_1.geometry}
          material={materials["Glass.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder037_2.geometry}
          material={materials["Metal.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder037_3.geometry}
          material={materials["Metal_Vers.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder031.geometry}
        material={materials["Metal.001"]}
        position={[-1.7, 0.2, 0.6]}
        scale={[0.9, 0.2, 0.9]}
      />
      <group position={[-1.7, 1.3, 0.6]} scale={0.9}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_1.geometry}
          material={materials["Metal_Vers.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_2.geometry}
          material={materials["Metal.001"]}
        />
      </group>
      <group
        position={[-1.3, 0.54, -1.4]}
        rotation={[0, -Math.PI / 6, 0]}
        scale={0.9}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder038_1.geometry}
          material={materials["Metal.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder038_2.geometry}
          material={materials.Liquide}
        />
      </group>
      <group position={[-1.3, 2.7, -1.4]} scale={0.3}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials["Metal_Vers.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_2.geometry}
          material={materials["Metal.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve008.geometry}
        material={materials["Glass.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve009.geometry}
        material={materials["Glass.001"]}
        position={[-0.004, 0, -0.001]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve010.geometry}
        material={materials["Glass.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials["Metal.001"]}
        position={[-0.7, 1.447, -0.6]}
        rotation={[Math.PI, -1.396, Math.PI]}
        scale={[0.191, 0.152, 0.191]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere009.geometry}
        material={materials["Glass.003"]}
        position={[-0.7, 1.51, -0.6]}
        rotation={[0.436, 0, 0]}
        scale={0.252}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={materials["Wood.002"]}
        position={[-0.388, 0.971, -0.849]}
        rotation={[-Math.PI, -0.698, 2.88]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere010.geometry}
        material={materials["Wood.002"]}
        position={[-0.7, 1.51, -0.6]}
        rotation={[0.436, 0, 0]}
        scale={0.252}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere011.geometry}
        material={materials["Liquide.001"]}
        position={[-0.7, 1.51, -0.6]}
        scale={0.227}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere.geometry}
        material={materials.Flame}
        position={[-0.56, 1.23, -0.6]}
        rotation={[0, 0, -0.665]}
        scale={0.028}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mball011.geometry}
        material={materials.Liquide}
        position={[-1.3, 1, -1.46]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere007.geometry}
        material={materials["Metal_Vers.002"]}
        position={[0, 1.8, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus.geometry}
        material={materials["Metal.001"]}
        position={[0, 1.33, 0.5]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.Logo}
        position={[0, 3, 0]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["base-mesh"].geometry}
        material={materials.Crane}
        position={[0.416, 0.913, 1.57]}
        rotation={[-2.281, 0.713, 2.491]}
        scale={0.76}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve.geometry}
        material={materials["Wood.001"]}
        position={[0.5, 1.04, 1.7]}
        rotation={[0.593, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve001.geometry}
        material={materials["Wood.001"]}
        position={[0.49, 1.14, 1.7]}
        rotation={[0.593, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve002.geometry}
        material={nodes.BezierCurve002.material}
        position={[0.68, 0.312, 1.228]}
        rotation={[Math.PI / 2, 0, 0.436]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve003.geometry}
        material={nodes.BezierCurve003.material}
        position={[0.75, 0.312, 1.318]}
        rotation={[Math.PI / 2, 0, -0.175]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve004.geometry}
        material={nodes.BezierCurve004.material}
        position={[0.79, 0.312, 1.118]}
        rotation={[Math.PI / 2, 0, 1.222]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve005.geometry}
        material={nodes.BezierCurve005.material}
        position={[0.72, 0.312, 1.398]}
        rotation={[Math.PI / 2, 0, Math.PI / 9]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve006.geometry}
        material={nodes.BezierCurve006.material}
        position={[0.68, 0.312, 1.508]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCurve007.geometry}
        material={nodes.BezierCurve007.material}
        position={[0.66, 0.313, 1.528]}
        rotation={[Math.PI / 2, 0, -0.087]}
        scale={0.08}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials["Metal.001"]}
        position={[0.27, 0.4, 1.04]}
        scale={0.042}
      />
      <group position={[0.4, 0.901, 1.431]} scale={[0.04, 0.03, 0.04]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cone_1.geometry}
          material={materials["Glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cone_2.geometry}
          material={materials["Metal.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Wood.001"]}
        position={[0.29, 0.5, 1.3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Wood.001"]}
        position={[0.7, 0.3, 1.3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Wood.001"]}
        position={[1.01, 0.19, 1.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.Crane}
        position={[0.67, 0.372, 1.05]}
        rotation={[-0.96, 0, 0]}
        scale={[0.012, 0.041, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials["Wood.002"]}
        position={[0.32, 0.357, 1.288]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[0.41, 0.915, 1.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials["Wood.001"]}
        position={[0.5, 0.05, 1.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials["Wood.001"]}
        position={[0.84, 0.01, 1.54]}
        scale={[0.018, 0.01, 0.018]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials["Metal.001"]}
        position={[0.67, 0.322, 1.099]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials.Room}
        position={[0.67, 0.35, 1.082]}
        rotation={[-0.96, 0, 0]}
        scale={[0.002, 0.034, 0.002]}
        
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={materials["Glass.001"]}
        position={[0.32, 0.42, 1.34]}
      />
      <group position={[0.39, 0.355, 1.56]} scale={0.048}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_1.geometry}
          material={materials["Glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019_2.geometry}
          material={materials["Wood.002"]}
        />
      </group>
      <group position={[0.388, 0.725, 1.17]} scale={1.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022_1.geometry}
          material={materials["Glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022_2.geometry}
          material={materials["Wood.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018.geometry}
        material={materials["Glass.001"]}
        position={[0.405, 0.733, 1.28]}
        scale={[1.13, 0.6, 1.13]}
      />
      <group position={[0.36, 0.72, 1.34]} scale={[0.044, 0.05, 0.044]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder025_1.geometry}
          material={materials["Glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder025_2.geometry}
          material={materials["Wood.002"]}
        />
      </group>
      <group position={[0.41, 0.715, 1.441]} scale={0.045}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder026_1.geometry}
          material={materials["Glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder026_2.geometry}
          material={materials["Wood.002"]}
        />
      </group>
      <group position={[0.37, 0.706, 1.53]} scale={0.036}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027.geometry}
          material={materials["Glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder027_1.geometry}
          material={materials["Wood.002"]}
        />
      </group>
      <group position={[0.42, 0.706, 1.6]} scale={0.036}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder028.geometry}
          material={materials["Glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder028_1.geometry}
          material={materials["Wood.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder023.geometry}
        material={materials["Wood.002"]}
        position={[0.41, 0.849, 1.26]}
        scale={[0.04, 0.008, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder024.geometry}
        material={materials["Metal.001"]}
        position={[0.41, 0.905, 1.26]}
        rotation={[-1.298, -0.286, 0.079]}
        scale={[0.054, 0.004, 0.054]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder025.geometry}
        material={materials["Metal_Vers.002"]}
        position={[0.41, 0.905, 1.26]}
        rotation={[0.147, 0.056, -2.779]}
        scale={[0.061, 0.004, 0.061]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002.geometry}
        material={materials["Wood.001"]}
        position={[0.5, 1.04, 1.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere003.geometry}
        material={materials["Wood.001"]}
        position={[0.5, 1.16, 1.7]}
      />
      <group
        position={[0.27, 0.419, 1.04]}
        rotation={[-Math.PI, -1.257, 2.723]}
        scale={0.046}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere004_1.geometry}
          material={materials["Glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Sphere004_2.geometry}
          material={materials["Wood.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere005.geometry}
        material={materials.Crane}
        position={[0.41, 0.905, 1.26]}
        scale={0.047}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["Metal.001"]}
        position={[0.22, 0.62, 1.61]}
        scale={[1, 1, 0.549]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials["Metal.001"]}
        position={[0.32, 0.962, 1.61]}
        scale={[1, 1, 0.549]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials["Livre.003"]}
        position={[0.4, 1.082, 1.43]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials["Livre.001"]}
        position={[0.4, 1.082, 1.404]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials["Livre.002"]}
        position={[0.4, 1.082, 1.378]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials["Livre.002"]}
        position={[0.4, 1.075, 1.459]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials["Livre.004"]}
        position={[0.4, 1.079, 1.489]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials["Livre.001"]}
        position={[0.4, 1.068, 1.331]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials["Livre.003"]}
        position={[0.4, 1.075, 1.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials["Livre.004"]}
        position={[0.4, 1.082, 1.251]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials["Livre.003"]}
        position={[0.4, 1.069, 1.518]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials["Livre.004"]}
        position={[0.4, 1.054, 1.225]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={materials["Livre.001"]}
        position={[0.4, 1.075, 1.196]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials["Livre.002"]}
        position={[0.4, 1.082, 1.167]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials["Livre.004"]}
        position={[0.4, 1.062, 1.138]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials["Livre.003"]}
        position={[0.4, 1.081, 1.017]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials["Livre.002"]}
        position={[0.4, 1.074, 1.046]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={materials["Livre.001"]}
        position={[0.4, 1.078, 1.076]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials["Livre.003"]}
        position={[0.4, 1.068, 1.106]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={materials["Livre.002"]}
        position={[0.4, 1.082, 1.599]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials["Livre.004"]}
        position={[0.4, 1.082, 1.573]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        material={materials["Livre.001"]}
        position={[0.4, 1.082, 1.547]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder033.geometry}
        material={materials["Liquide.001"]}
        position={[0.388, 0.724, 1.17]}
        scale={1.015}
      />
      <group position={[0.371, 0.725, 1.072]} scale={1.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder017_1.geometry}
          material={materials["Glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder017_2.geometry}
          material={materials["Wood.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder035.geometry}
        material={materials["Liquide.001"]}
        position={[0.371, 0.724, 1.072]}
        scale={1.015}
      />
      <group position={[0.407, 0.725, 0.99]} scale={1.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder029.geometry}
          material={materials["Glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder029_1.geometry}
          material={materials["Wood.002"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder037.geometry}
        material={materials["Liquide.001"]}
        position={[0.407, 0.724, 0.99]}
        scale={1.015}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials.Liquide}
        position={[0.39, 0.355, 1.56]}
        scale={0.043}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder016.geometry}
        material={materials["Liquide.001"]}
        position={[0.41, 0.715, 1.441]}
        scale={0.041}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder038.geometry}
        material={materials["Liquide.001"]}
        position={[0.36, 0.72, 1.34]}
        scale={[0.04, 0.045, 0.04]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder039.geometry}
        material={materials["Liquide.001"]}
        position={[0.37, 0.706, 1.53]}
        scale={0.032}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder040.geometry}
        material={materials["Liquide.001"]}
        position={[0.42, 0.706, 1.6]}
        scale={0.032}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder041.geometry}
        material={materials["Liquide.001"]}
        position={[0.405, 0.723, 1.28]}
        scale={[1.084, 0.576, 1.084]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere008.geometry}
        material={materials["Liquide.001"]}
        position={[0.27, 0.419, 1.04]}
        scale={0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.Room}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder_1.geometry}
        material={materials.Floor}
      />
    </group>
  );
}

useGLTF.preload("/models/Demo_Room-002.glb");
