/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useContext, useEffect, useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';

import Enigma from '../enigmas/Enigma';
import useInteractiveObject from '../../../hooks/useInteractiveObject';
import { SocketContext } from '../../../contexts/SocketContext';
import { ClientToServer } from '../../../data/socketMessages';
import BasicDisplayTemplate from '../enigmas/BasicEnigmaDisplay';
import InformationPopup from '../informations/InformationPopup';

export default function Model(props) {
	const socket = useContext(SocketContext);

	useEffect(() => {
		socket.emit(ClientToServer.RoomLoaded);
	});

	const { nodes, materials } = useGLTF("models/Demo_Room-001.glb");

	const SuzanneEvent = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
			forceExit,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Cube001"
				castShadow
				receiveShadow
				geometry={nodes.Cube001.geometry}
				material={materials["Wood.002"]}
				position={[1, 1, -1.5]}
				scale={[1, 0.03, 0.5]}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0x00ff00} />}
				{clicked && (
					<Enigma
						enigmaId={0}
						enigmaDisplayTemplate={(data, handleSubmitAnswer) => (
							<BasicDisplayTemplate
								title="Salut Gnibo!"
								description="Je suis un singe! La réponse est 1."
								image={data.image}
								handleSubmitAnswer={handleSubmitAnswer}
							/>
						)}
						closeEnigma={forceExit}
					/>
				)}
			</mesh>
		);
	};

	return (
		<group {...props} dispose={null}>
			<group name="Scene">
				<mesh
					name="Cube"
					castShadow
					receiveShadow
					geometry={nodes.Cube.geometry}
					material={materials.Room}
					position={[0, 2, 0]}
					scale={2}
				/>
				{/*<mesh
					name="Cube001"
					castShadow
					receiveShadow
					geometry={nodes.Cube001.geometry}
					material={materials["Wood.002"]}
					position={[1, 1, -1.5]}
					scale={[1, 0.03, 0.5]}
				>*/}
				<SuzanneEvent />
				<mesh
					name="Cube002"
					castShadow
					receiveShadow
					geometry={nodes.Cube002.geometry}
					material={materials["Wood.002"]}
					position={[0.1, 0.899, -1.1]}
					scale={[0.033, 0.1, 0.033]}
				/>
				<mesh
					name="Cube003"
					castShadow
					receiveShadow
					geometry={nodes.Cube003.geometry}
					material={nodes.Cube003.material}
					position={[1.5, 1.41, -1.7]}
					scale={0.28}
				/>
				<mesh
					name="Cube004"
					castShadow
					receiveShadow
					geometry={nodes.Cube004.geometry}
					material={nodes.Cube004.material}
					position={[1.5, 1.04, -1.21]}
				/>
				<mesh
					name="Cube005"
					castShadow
					receiveShadow
					geometry={nodes.Cube005.geometry}
					material={nodes.Cube005.material}
					position={[1.3, 1.06, -1.305]}
					scale={0.015}
				/>
				<mesh
					name="Cube006"
					castShadow
					receiveShadow
					geometry={nodes.Cube006.geometry}
					material={nodes.Cube006.material}
					position={[1.3, 1.06, -1.113]}
					scale={0.015}
				/>
				<mesh
					name="Cube007"
					castShadow
					receiveShadow
					geometry={nodes.Cube007.geometry}
					material={nodes.Cube007.material}
					position={[1.331, 1.06, -1.113]}
					scale={0.015}
				/>
				<mesh
					name="Cube008"
					castShadow
					receiveShadow
					geometry={nodes.Cube008.geometry}
					material={nodes.Cube008.material}
					position={[1.362, 1.06, -1.113]}
					scale={0.015}
				/>
				<mesh
					name="Cube009"
					castShadow
					receiveShadow
					geometry={nodes.Cube009.geometry}
					material={nodes.Cube009.material}
					position={[1.393, 1.06, -1.113]}
					scale={0.015}
				/>
				<mesh
					name="Cube010"
					castShadow
					receiveShadow
					geometry={nodes.Cube010.geometry}
					material={nodes.Cube010.material}
					position={[1.578, 1.06, -1.113]}
					scale={0.015}
				/>
				<mesh
					name="Cube011"
					castShadow
					receiveShadow
					geometry={nodes.Cube011.geometry}
					material={nodes.Cube011.material}
					position={[1.609, 1.06, -1.113]}
					scale={0.015}
				/>
				<mesh
					name="Cube012"
					castShadow
					receiveShadow
					geometry={nodes.Cube012.geometry}
					material={nodes.Cube012.material}
					position={[1.64, 1.06, -1.113]}
					scale={0.015}
				/>
				<mesh
					name="Cube013"
					castShadow
					receiveShadow
					geometry={nodes.Cube013.geometry}
					material={nodes.Cube013.material}
					position={[1.671, 1.06, -1.113]}
					scale={0.015}
				/>
				<mesh
					name="Cube014"
					castShadow
					receiveShadow
					geometry={nodes.Cube014.geometry}
					material={materials["Wood.002"]}
					position={[-0.18, 0.4, -1.59]}
					rotation={[0, -1.571, 0]}
				/>
				<mesh
					name="Cylinder"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder.geometry}
					material={materials["Metal.001"]}
					position={[0.5, 0.2, -1]}
					scale={0.2}
				>
					<mesh
						name="Cylinder001"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder001.geometry}
						material={materials["Metal_Orange.002"]}
					/>
				</mesh>
				<group name="Cube015" position={[1.3, 0.3, 1.6]}>
					<mesh
						name="Cube016_1"
						castShadow
						receiveShadow
						geometry={nodes.Cube016_1.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Cube016_2"
						castShadow
						receiveShadow
						geometry={nodes.Cube016_2.geometry}
						material={materials["Metal_Orange.002"]}
					/>
				</group>
				<mesh
					name="Cube016"
					castShadow
					receiveShadow
					geometry={nodes.Cube016.geometry}
					material={materials["Wood.002"]}
					position={[1.3, 0.6, -0.2]}
					rotation={[0, Math.PI / 9, 0]}
					scale={[0.28, 0.028, 0.28]}
				/>
				<mesh
					name="Cylinder002"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder002.geometry}
					material={nodes.Cylinder002.material}
					position={[0.39, 1.046, -1.7]}
					rotation={[Math.PI, -0.96, Math.PI]}
					scale={[-0.16, -0.016, -0.16]}
				>
					<mesh
						name="Cube017"
						castShadow
						receiveShadow
						geometry={nodes.Cube017.geometry}
						material={nodes.Cube017.material}
						position={[-0.512, -0.875, 0.358]}
						rotation={[-Math.PI, 0.96, -Math.PI]}
						scale={[-0.125, -0.5, -0.125]}
					/>
					<mesh
						name="Sphere"
						castShadow
						receiveShadow
						geometry={nodes.Sphere.geometry}
						material={nodes.Sphere.material}
						position={[0, -24, 1.55]}
						rotation={[-Math.PI, 0, -Math.PI]}
						scale={[-0.27, -2.7, -0.27]}
					/>
				</mesh>
				<group name="Cube018" position={[-1, 1.4, 1.96]}>
					<mesh
						name="Cube019_1"
						castShadow
						receiveShadow
						geometry={nodes.Cube019_1.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Cube019_2"
						castShadow
						receiveShadow
						geometry={nodes.Cube019_2.geometry}
						material={materials["Metal_Orange.002"]}
					/>
				</group>
				<mesh
					name="Cube019"
					castShadow
					receiveShadow
					geometry={nodes.Cube019.geometry}
					material={nodes.Cube019.material}
					position={[0, 2, 0]}
					scale={2}
				/>
				<mesh
					name="Cube020"
					castShadow
					receiveShadow
					geometry={nodes.Cube020.geometry}
					material={nodes.Cube020.material}
					position={[0, 2, 0]}
					scale={2}
				/>
				<mesh
					name="Cube021"
					castShadow
					receiveShadow
					geometry={nodes.Cube021.geometry}
					material={nodes.Cube021.material}
					position={[0, 2, 0]}
					scale={2}
				/>
				<mesh
					name="BezierCurve"
					castShadow
					receiveShadow
					geometry={nodes.BezierCurve.geometry}
					material={nodes.BezierCurve.material}
					position={[0.95, 1.031, -1.38]}
					rotation={[Math.PI / 2, 0, Math.PI / 2]}
					scale={0.231}
				/>
				<mesh
					name="BezierCurve001"
					castShadow
					receiveShadow
					geometry={nodes.BezierCurve001.geometry}
					material={nodes.BezierCurve001.material}
					position={[0.65, 1.031, -1.48]}
					rotation={[Math.PI / 2, 0, 1.92]}
					scale={0.231}
				/>
				<mesh
					name="BezierCurve002"
					castShadow
					receiveShadow
					geometry={nodes.BezierCurve002.geometry}
					material={nodes.BezierCurve002.material}
					position={[0.98, 1.042, -1.58]}
					rotation={[Math.PI / 2, 0, 1.309]}
					scale={0.231}
				/>
				<mesh
					name="BezierCurve003"
					castShadow
					receiveShadow
					geometry={nodes.BezierCurve003.geometry}
					material={nodes.BezierCurve003.material}
					position={[0.25, 1.031, -1.28]}
					rotation={[Math.PI / 2, 0, 1.222]}
					scale={0.231}
				/>
				<mesh
					name="BezierCurve004"
					castShadow
					receiveShadow
					geometry={nodes.BezierCurve004.geometry}
					material={nodes.BezierCurve004.material}
					position={[1.15, 2.331, -1.999]}
					rotation={[-Math.PI, 0, Math.PI / 2]}
					scale={0.503}
				/>
				<mesh
					name="Cube022"
					castShadow
					receiveShadow
					geometry={nodes.Cube022.geometry}
					material={nodes.Cube022.material}
					position={[2, 2.092, 0.5]}
				/>
				<mesh
					name="Cylinder003"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder003.geometry}
					material={materials.Room}
					position={[-1, 5, -8]}
					scale={[4, 5, 4]}
				/>
				<mesh
					name="Cylinder004"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder004.geometry}
					material={nodes.Cylinder004.material}
					position={[-1, 5, -8]}
					scale={[4, 5, 4]}
				/>
				<mesh
					name="Cylinder006"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder006.geometry}
					material={nodes.Cylinder006.material}
					position={[-1, 5, -8]}
					scale={[4, 5, 4]}
				/>
				<mesh
					name="Cylinder005"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder005.geometry}
					material={nodes.Cylinder005.material}
					position={[-1, 0.4, -9.8]}
					scale={[1.79, 0.4, 1.79]}
				/>
				<mesh
					name="Icosphere"
					castShadow
					receiveShadow
					geometry={nodes.Icosphere.geometry}
					material={nodes.Icosphere.material}
					position={[-1, 1.9, -10.3]}
					scale={1.04}
				/>
				<mesh
					name="Icosphere001"
					castShadow
					receiveShadow
					geometry={nodes.Icosphere001.geometry}
					material={materials["Metal.001"]}
					position={[-1, 1.9, -10.3]}
					scale={1.3}
				/>
				<mesh
					name="Cylinder007"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder007.geometry}
					material={nodes.Cylinder007.material}
					position={[-1, 5, -8]}
					scale={[4, 5, 4]}
				/>
				<mesh
					name="Cylinder008"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder008.geometry}
					material={nodes.Cylinder008.material}
					position={[2.2, 0.5, -8.3]}
					scale={[0.42, 0.5, 0.42]}
				/>
				<mesh
					name="Cylinder009"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder009.geometry}
					material={nodes.Cylinder009.material}
					position={[-1, 5, -8]}
					scale={[4, 5, 4]}
				/>
				<mesh
					name="Cylinder010"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder010.geometry}
					material={nodes.Cylinder010.material}
					position={[2, 0.5, -7]}
					scale={[0.42, 0.5, 0.42]}
				/>
				<mesh
					name="Cylinder011"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder011.geometry}
					material={nodes.Cylinder011.material}
					position={[1.3, 0.5, -5.9]}
					scale={[0.42, 0.5, 0.42]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("models/Demo_Room-001.glb");
