/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useContext, useEffect, useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';

import Enigma from '../enigmas/Enigma';
import useInteractiveObject from '../../../hooks/useInteractiveObject';
import { SocketContext } from '../../../contexts/SocketContext';
import { ClientToServer } from '../../../data/socketMessages';
import BasicDisplayTemplate from '../enigmas/BasicEnigmaDisplay';
import InformationPopup from '../informations/InformationPopup';
import InfoPopupSlider from '../informations/InfoPopupSlider';
import EnigmaCoffreDisplay from '../enigmas/EnigmaCoffreDisplay';
import EnigmaChaufDisplay from '../enigmas/EnigmaChaufDisplay';

import la_recette from '../../../assets/img/la_recette.png';
import NoteLab from '../../../assets/img/Notes_lab.png';
import fonctionLab from '../../../assets/img/fonction_lab.png';

export default function Room001(props) {
	const images = [
		la_recette,
		fonctionLab,
		NoteLab,
	];

	const socket = useContext(SocketContext);

	useEffect(() => {
		socket.emit(ClientToServer.RoomLoaded);
	});

	const { nodes, materials } = useGLTF('models/Laboratory_Room.glb');

	const mesh = useRef();

	const PorteInt = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
			forceExit,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Cube015"
				castShadow
				receiveShadow
				geometry={nodes.Cube015.geometry}
				material={materials["Metal.001"]}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0x00ff00} />}
				{clicked && (
					<InformationPopup
						title="Vous ne pouvez pas sortir !"
						closePopup={forceExit}>
						<p>Tu es amateur {"d'alchimie"} et en voulant {"t'introduire"} dans le laboratoire {"d'un"} grand alchimiste, tu as été malencontreusement enfermé !
							Le scientifique ne tardera pas à revenir... Vous remarquez un <strong>trou</strong> dans la porte, il y a surement moyen de faire une <strong>potion de souris</strong> pour que vous rapetissiez.
							<br />Regardez autour de vous, il doit bien y avoir une <strong>recette</strong> qui peut vous aidez !</p>
					</InformationPopup>
				)}
			</mesh>
		);
	};

	const FeuilleInt = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
			forceExit,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Feuilles"
				castShadow
				receiveShadow
				geometry={nodes.Feuilles.geometry}
				material={materials.Default}
				position={[0.75, 0.312, 1.318]}
				rotation={[Math.PI / 2, 0, -0.175]}
				scale={0.08}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0x00ff00} />}
				{clicked && (
					<InfoPopupSlider
						title="Recette de potion de Nano"
						images={images}
						closePopup={forceExit}>
						<p>Cette recette vous dit quelque chose... Ça a {"l'air d'être"} une <strong>recette alternative</strong> à la potion de souris !</p>
					</InfoPopupSlider>
				)}
			</mesh>
		);
	};

	const ArmoirInt = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
			forceExit,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Armoir"
				castShadow
				receiveShadow
				geometry={nodes.Armoir.geometry}
				material={materials['Wood.001']}
				position={[1.3, 0.7, -1.85]}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0x00ff00} />}
				{clicked && (
					<Enigma
						title='Étagère'
						enigmaId={0}
						enigmaDisplayTemplate={(data, hint, isSolved, handleSubmitAnswer, handleAskHint) => (
							<BasicDisplayTemplate
								title="L'ingrédient que vous cherchez doit être ici !"
								description="Encore faut-il trouver le bon tiroir..."
								hint={hint}
								isSolved={isSolved}
								image={data.image}
								handleSubmitAnswer={handleSubmitAnswer}
								handleAskHint={handleAskHint}
							/>
						)}
						closeEnigma={forceExit}
					/>
				)}
			</mesh>
		);
	};

	const CoffreInt = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
			forceExit,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Cube010"
				castShadow
				receiveShadow
				geometry={nodes.Cube010.geometry}
				material={materials['Metal.001']}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0x00ff00} />}
				{clicked && (
					<Enigma
						enigmaId={1}
						enigmaDisplayTemplate={(data, hint, isSolved, handleSubmitAnswer, handleAskHint) => (
							<EnigmaCoffreDisplay
								handleSubmitAnswer={handleSubmitAnswer}
								title="OOH un coffre !"
								description="Vous vous en doutiez mais il faut un code."
								image={data.image}
								hint={hint}
								isSolved={isSolved}
								handleAskHint={handleAskHint}
							/>
						)}
						closeEnigma={forceExit}
					/>
				)}
			</mesh>
		);
	};

	const MelangeurInt = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
			forceExit,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Sphere"
				castShadow
				receiveShadow
				geometry={nodes.Sphere.geometry}
				material={materials['Metal.001']}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0x00ff00} />}
				{clicked && (
					<Enigma
						enigmaId={2}
						enigmaDisplayTemplate={(data, hint, isSolved, handleSubmitAnswer, handleAskHint) => (
							<BasicDisplayTemplate
								title="Une bonne mixture !"
								description="Mais pendant combien de temps il faut melanger ?"
								hint={hint}
								isSolved={isSolved}
								image={data.image}
								handleSubmitAnswer={handleSubmitAnswer}
								handleAskHint={handleAskHint}
							/>
						)}
						closeEnigma={forceExit}
					/>
				)}
			</mesh>
		);
	};

	const CuisssonInt = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
			forceExit,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Cylinder035_1"
				castShadow
				receiveShadow
				geometry={nodes.Cylinder035_1.geometry}
				material={materials["Metal_Vers.002"]}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0x00ff00} />}
				{clicked && (
					<Enigma
						enigmaId={3}
						enigmaDisplayTemplate={(data, hint, isSolved, handleSubmitAnswer, handleAskHint) => (
							<EnigmaChaufDisplay
								title="Chaud devant !"
								description="La potion est presque terminée, mais il ne faut pas la faire bruler !"
								hint={hint}
								isSolved={isSolved}
								image={data.image}
								handleSubmitAnswer={handleSubmitAnswer}
								handleAskHint={handleAskHint}
								stepButton={50}
							/>
						)}
						closeEnigma={forceExit}
					/>
				)}
			</mesh>
		);
	};


	return (
		<group {...props} dispose={null}>
			<group name="Scene">
				<mesh
					name="Cube"
					castShadow
					receiveShadow
					geometry={nodes.Cube.geometry}
					material={materials.Crane}
					position={[1.302, 0.864, -1.692]}
					scale={[0.673, 0.003, 0.008]}
				/>
				<mesh
					name="Cadre_porte"
					castShadow
					receiveShadow
					geometry={nodes.Cadre_porte.geometry}
					material={materials["Wood.002"]}
					position={[1.6, 0.5, 1.98]}
					rotation={[0, -1.571, 0]}
				/>
				<group
					name="Porte"
					position={[1.6, 0.5, 1.988]}
					rotation={[0, -1.571, 0]}
					scale={[0.6, 1, 1]}
				>
					{/* Remplacer le mesh par le composant PorteInt
					<mesh
						name="Cube015"
						castShadow
						receiveShadow
						geometry={nodes.Cube015.geometry}
						material={materials["Metal.001"]}
					/>
					*/}
					<PorteInt />
					<mesh
						name="Cube015_1"
						castShadow
						receiveShadow
						geometry={nodes.Cube015_1.geometry}
						material={materials["Metal_Vers.002"]}
					/>
				</group>
				<group name="Room">
					<mesh
						name="Cylinder"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder.geometry}
						material={materials.Room}
					/>
					<mesh
						name="Cylinder_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder_1.geometry}
						material={materials.Floor}
					/>
				</group>
				<group
					name="Cuve001"
					position={[0, 1.8, 0]}
					rotation={[0, 0, -Math.PI / 2]}
				>
					{/* Remplacer le mesh par le composant MelangeurInt
						<mesh
							name="Sphere"
							castShadow
							receiveShadow
							geometry={nodes.Sphere.geometry}
							material={materials["Metal.001"]}
						/>
					*/}
					<MelangeurInt />
					<mesh
						name="Sphere_1"
						castShadow
						receiveShadow
						geometry={nodes.Sphere_1.geometry}
						material={materials["Metal_Vers.002"]}
					/>
					<mesh
						name="Sphere_2"
						castShadow
						receiveShadow
						geometry={nodes.Sphere_2.geometry}
						material={materials.Liquide}
					/>
				</group>
				<group name="Verseur" position={[0, 1.19, 0]}>
					<mesh
						name="Sphere001"
						castShadow
						receiveShadow
						geometry={nodes.Sphere001.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Sphere001_1"
						castShadow
						receiveShadow
						geometry={nodes.Sphere001_1.geometry}
						material={materials["Metal_Vers.002"]}
					/>
				</group>
				<mesh
					name="Marmite"
					castShadow
					receiveShadow
					geometry={nodes.Marmite.geometry}
					material={materials["Metal.001"]}
					position={[0, 0.1, 0]}
				/>
				<group
					name="Cylinder002"
					position={[0, 1.39, 0]}
					scale={[0.12, 0.03, 0.12]}
				>
					<mesh
						name="Cylinder003"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder003.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Cylinder003_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder003_1.geometry}
						material={materials["Metal_Vers.002"]}
					/>
				</group>
				<mesh
					name="Pipe004"
					castShadow
					receiveShadow
					geometry={nodes.Pipe004.geometry}
					material={materials["Metal_Vers.002"]}
					position={[0.25, 2.27, 0]}
					scale={[0.027, 0.2, 0.027]}
				/>
				<group name="Cylinder008" position={[0, 2.5, 0]}>
					<mesh
						name="Cylinder009"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder009.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Cylinder009_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder009_1.geometry}
						material={materials["Metal_Vers.002"]}
					/>
				</group>
				<group name="Chaud" position={[-0.7, 0.4, -0.6]}>
					{/* Remplacer le mesh par le composant CuisssonInt
						<mesh
							name="Cylinder035_1"
							castShadow
							receiveShadow
							geometry={nodes.Cylinder035_1.geometry}
							material={materials["Metal_Vers.002"]}
						/>
					*/}
					<CuisssonInt />
					<mesh
						name="Cylinder035_2"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder035_2.geometry}
						material={materials["Metal.001"]}
					/>
				</group>
				{/* Remplacer le mesh par le composant ArmoirInt
					<mesh
						name="Armoir"
						castShadow
						receiveShadow
						geometry={nodes.Armoir.geometry}
						material={materials["Wood.001"]}
						position={[1.3, 0.7, -1.85]}
					/>
				*/}
				<ArmoirInt />
				<group
					name="Rangement"
					position={[0.72, 1.28, -1.83]}
					scale={[0.08, 0.08, 0.14]}
				>
					<mesh
						name="Cube012"
						castShadow
						receiveShadow
						geometry={nodes.Cube012.geometry}
						material={materials["Wood.002"]}
					/>
					<mesh
						name="Cube012_1"
						castShadow
						receiveShadow
						geometry={nodes.Cube012_1.geometry}
						material={materials["Metal_Vers.002"]}
					/>
				</group>
				<mesh
					name="Poigne"
					castShadow
					receiveShadow
					geometry={nodes.Poigne.geometry}
					material={materials["Metal_Vers.002"]}
					position={[0.72, 1.28, -1.66]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.02}
				/>
				<mesh
					name="Echelle001"
					castShadow
					receiveShadow
					geometry={nodes.Echelle001.geometry}
					material={materials["Wood.002"]}
					position={[0.462, 0.971, -1.829]}
					rotation={[0, 0, -0.262]}
				/>
				<group name="Cuve003" position={[-1.7, 1.3, 0.6]}>
					<mesh
						name="Cylinder037_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder037_1.geometry}
						material={materials["Glass.002"]}
					/>
					<mesh
						name="Cylinder037_2"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder037_2.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Cylinder037_3"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder037_3.geometry}
						material={materials["Metal_Vers.002"]}
					/>
				</group>
				<mesh
					name="Support_Cuve"
					castShadow
					receiveShadow
					geometry={nodes.Support_Cuve.geometry}
					material={materials["Metal.001"]}
					position={[-1.7, 0.2, 0.6]}
					scale={[0.9, 0.2, 0.9]}
				/>
				<group name="Cylinder032" position={[-1.7, 1.3, 0.6]} scale={0.9}>
					<mesh
						name="Cylinder015_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder015_1.geometry}
						material={materials["Metal_Vers.002"]}
					/>
					<mesh
						name="Cylinder015_2"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder015_2.geometry}
						material={materials["Metal.001"]}
					/>
				</group>
				<group
					name="Cuve002"
					position={[-1.3, 0.54, -1.4]}
					rotation={[0, -Math.PI / 6, 0]}
					scale={0.9}
				>
					<mesh
						name="Cylinder038_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder038_1.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Cylinder038_2"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder038_2.geometry}
						material={materials.Liquide}
					/>
				</group>
				<group name="Hote" position={[-1.3, 2.7, -1.4]} scale={0.3}>
					<mesh
						name="Cylinder001"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder001.geometry}
						material={materials["Metal_Vers.002"]}
					/>
					<mesh
						name="Cylinder001_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder001_1.geometry}
						material={materials["Metal.001"]}
					/>
				</group>
				<mesh
					name="Pipe002"
					castShadow
					receiveShadow
					geometry={nodes.Pipe002.geometry}
					material={materials["Glass.001"]}
				/>
				<mesh
					name="Pipe003"
					castShadow
					receiveShadow
					geometry={nodes.Pipe003.geometry}
					material={materials["Glass.001"]}
					position={[-0.004, 0, -0.001]}
				/>
				<mesh
					name="Pipe001"
					castShadow
					receiveShadow
					geometry={nodes.Pipe001.geometry}
					material={materials["Glass.001"]}
				/>
				<mesh
					name="Porte_Potion001"
					castShadow
					receiveShadow
					geometry={nodes.Porte_Potion001.geometry}
					material={materials["Metal.001"]}
					position={[-0.7, 1.447, -0.6]}
					rotation={[Math.PI, -1.396, Math.PI]}
					scale={[0.191, 0.152, 0.191]}
				/>
				<mesh
					name="Potion010"
					castShadow
					receiveShadow
					geometry={nodes.Potion010.geometry}
					material={materials["Glass.003"]}
					position={[-0.7, 1.51, -0.6]}
					rotation={[0.436, 0, 0]}
					scale={0.252}
				/>
				<mesh
					name="Echelle002"
					castShadow
					receiveShadow
					geometry={nodes.Echelle002.geometry}
					material={materials["Wood.002"]}
					position={[-0.388, 0.971, -0.849]}
					rotation={[-Math.PI, -0.698, 2.88]}
				/>
				<mesh
					name="Bouchon"
					castShadow
					receiveShadow
					geometry={nodes.Bouchon.geometry}
					material={materials["Wood.002"]}
					position={[-0.7, 1.51, -0.6]}
					rotation={[0.436, 0, 0]}
					scale={0.252}
				/>
				<mesh
					name="Sphere011"
					castShadow
					receiveShadow
					geometry={nodes.Sphere011.geometry}
					material={materials["Liquide.001"]}
					position={[-0.7, 1.51, -0.6]}
					scale={0.227}
				/>
				<mesh
					name="Flame"
					castShadow
					receiveShadow
					geometry={nodes.Flame.geometry}
					material={materials.Flame}
					position={[-0.56, 1.23, -0.6]}
					rotation={[0, 0, -0.665]}
					scale={0.028}
				/>
				<mesh
					name="Mball011"
					castShadow
					receiveShadow
					geometry={nodes.Mball011.geometry}
					material={materials.Liquide}
					position={[-1.3, 1, -1.46]}
				/>
				<mesh
					name="Chaine"
					castShadow
					receiveShadow
					geometry={nodes.Chaine.geometry}
					material={materials["Metal.001"]}
					position={[0, 1.33, 0.5]}
				/>
				<mesh
					name="Plane"
					castShadow
					receiveShadow
					geometry={nodes.Plane.geometry}
					material={materials.Logo}
					position={[0, 3, 0]}
					scale={0.3}
				/>
				<mesh
					name="Masque"
					castShadow
					receiveShadow
					geometry={nodes.Masque.geometry}
					material={materials.Crane}
					position={[0.416, 0.913, 1.57]}
					rotation={[-2.281, 0.713, 2.491]}
					scale={0.76}
				/>
				<mesh
					name="Deco_Bureau"
					castShadow
					receiveShadow
					geometry={nodes.Deco_Bureau.geometry}
					material={materials["Wood.001"]}
					position={[0.5, 1.04, 1.7]}
					rotation={[0.593, -Math.PI / 2, 0]}
				/>
				<mesh
					name="Deco_Bureau001"
					castShadow
					receiveShadow
					geometry={nodes.Deco_Bureau001.geometry}
					material={materials["Wood.001"]}
					position={[0.49, 1.14, 1.7]}
					rotation={[0.593, -Math.PI / 2, 0]}
				/>
				{/* Remplacer le mesh par le composant FeuilleInt
					<mesh
						name="Feuilles"
						castShadow
						receiveShadow
						geometry={nodes.Feuilles.geometry}
						material={materials.Default}
						position={[0.75, 0.312, 1.318]}
						rotation={[Math.PI / 2, 0, -0.175]}
						scale={0.08}
					/>
				*/}
				<FeuilleInt />
				<mesh
					name="Porte_Potion"
					castShadow
					receiveShadow
					geometry={nodes.Porte_Potion.geometry}
					material={materials["Metal.001"]}
					position={[0.27, 0.4, 1.04]}
					scale={0.042}
				/>
				<group
					name="Sablier"
					position={[0.4, 0.901, 1.431]}
					scale={[0.04, 0.03, 0.04]}
				>
					<mesh
						name="Cone"
						castShadow
						receiveShadow
						geometry={nodes.Cone.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cone_1"
						castShadow
						receiveShadow
						geometry={nodes.Cone_1.geometry}
						material={materials["Metal.001"]}
					/>
				</group>
				<mesh
					name="Bureau"
					castShadow
					receiveShadow
					geometry={nodes.Bureau.geometry}
					material={materials["Wood.001"]}
					position={[0.29, 0.5, 1.3]}
				/>
				<mesh
					name="Table"
					castShadow
					receiveShadow
					geometry={nodes.Table.geometry}
					material={materials["Wood.001"]}
					position={[0.7, 0.3, 1.3]}
				/>
				<mesh
					name="Chaise"
					castShadow
					receiveShadow
					geometry={nodes.Chaise.geometry}
					material={materials["Wood.002"]}
					position={[1.01, 0.19, 1.31]}
				/>
				<mesh
					name="Support_Tube"
					castShadow
					receiveShadow
					geometry={nodes.Support_Tube.geometry}
					material={materials["Wood.002"]}
					position={[0.32, 0.357, 1.288]}
				/>
				<group name="Coffre" position={[0.41, 0.915, 1.04]}>
					{/* Remplacer le mesh par le composant CoffreInt
					<mesh
						name="Cube010"
						castShadow
						receiveShadow
						geometry={nodes.Cube010.geometry}
						material={materials["Metal.001"]}
					/>
					*/}
					<CoffreInt />
					<mesh
						name="Cube010_1"
						castShadow
						receiveShadow
						geometry={nodes.Cube010_1.geometry}
						material={materials["Metal_Vers.002"]}
					/>
				</group>
				<mesh
					name="ancre"
					castShadow
					receiveShadow
					geometry={nodes.ancre.geometry}
					material={materials["Metal.001"]}
					position={[0.67, 0.322, 1.099]}
				/>
				<group
					name="Plume"
					position={[0.67, 0.35, 1.082]}
					rotation={[-0.96, 0, 0]}
					scale={[0.002, 0.034, 0.002]}
				>
					<mesh
						name="Cylinder014"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder014.geometry}
						material={materials.Room}
					/>
					<mesh
						name="Cylinder014_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder014_1.geometry}
						material={materials.Crane}
					/>
				</group>
				<mesh
					name="Tube_Essai"
					castShadow
					receiveShadow
					geometry={nodes.Tube_Essai.geometry}
					material={materials["Glass.001"]}
					position={[0.32, 0.42, 1.34]}
				/>
				<group name="Potion002" position={[0.39, 0.355, 1.56]} scale={0.048}>
					<mesh
						name="Cylinder019"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder019.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder019_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder019_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<group name="Potion005" position={[0.388, 0.725, 1.17]} scale={1.1}>
					<mesh
						name="Cylinder022"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder022.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder022_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder022_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<mesh
					name="Potion006"
					castShadow
					receiveShadow
					geometry={nodes.Potion006.geometry}
					material={materials["Glass.001"]}
					position={[0.405, 0.733, 1.28]}
					scale={[1.13, 0.6, 1.13]}
				/>
				<group
					name="Potion007"
					position={[0.36, 0.72, 1.34]}
					scale={[0.044, 0.05, 0.044]}
				>
					<mesh
						name="Cylinder025"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder025.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder025_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder025_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<group name="Potion008" position={[0.41, 0.715, 1.441]} scale={0.045}>
					<mesh
						name="Cylinder026"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder026.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder026_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder026_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<group name="Potion009" position={[0.37, 0.706, 1.53]} scale={0.036}>
					<mesh
						name="Cylinder027"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder027.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder027_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder027_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<group name="Potion011" position={[0.42, 0.706, 1.6]} scale={0.036}>
					<mesh
						name="Cylinder028"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder028.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder028_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder028_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<mesh
					name="Sphere_Bureau"
					castShadow
					receiveShadow
					geometry={nodes.Sphere_Bureau.geometry}
					material={materials["Wood.002"]}
					position={[0.5, 1.16, 1.7]}
				/>
				<group
					name="Potion001"
					position={[0.27, 0.419, 1.04]}
					rotation={[-Math.PI, -1.257, 2.723]}
					scale={0.046}
				>
					<mesh
						name="Sphere004"
						castShadow
						receiveShadow
						geometry={nodes.Sphere004.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Sphere004_1"
						castShadow
						receiveShadow
						geometry={nodes.Sphere004_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<group name="Orbe" position={[0.41, 0.905, 1.26]}>
					<mesh
						name="Sphere005"
						castShadow
						receiveShadow
						geometry={nodes.Sphere005.geometry}
						material={materials.Crane}
					/>
					<mesh
						name="Sphere005_1"
						castShadow
						receiveShadow
						geometry={nodes.Sphere005_1.geometry}
						material={materials["Wood.002"]}
					/>
					<mesh
						name="Sphere005_2"
						castShadow
						receiveShadow
						geometry={nodes.Sphere005_2.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Sphere005_3"
						castShadow
						receiveShadow
						geometry={nodes.Sphere005_3.geometry}
						material={materials["Metal_Vers.002"]}
					/>
				</group>
				<mesh
					name="Support_Bureau"
					castShadow
					receiveShadow
					geometry={nodes.Support_Bureau.geometry}
					material={materials["Metal.001"]}
					position={[0.22, 0.62, 1.61]}
					scale={[1, 1, 0.549]}
				/>
				<mesh
					name="Support_Bureau001"
					castShadow
					receiveShadow
					geometry={nodes.Support_Bureau001.geometry}
					material={materials["Metal.001"]}
					position={[0.32, 0.962, 1.61]}
					scale={[1, 1, 0.549]}
				/>
				<mesh
					name="Livre001"
					castShadow
					receiveShadow
					geometry={nodes.Livre001.geometry}
					material={materials["Livre.004"]}
					position={[0.4, 1.062, 1.138]}
				/>
				<mesh
					name="Livre002"
					castShadow
					receiveShadow
					geometry={nodes.Livre002.geometry}
					material={materials["Livre.003"]}
					position={[0.4, 1.081, 1.017]}
				/>
				<mesh
					name="Livre003"
					castShadow
					receiveShadow
					geometry={nodes.Livre003.geometry}
					material={materials["Livre.001"]}
					position={[0.4, 1.078, 1.076]}
				/>
				<mesh
					name="Cube028"
					castShadow
					receiveShadow
					geometry={nodes.Cube028.geometry}
					material={materials["Livre.002"]}
					position={[0.4, 1.082, 1.599]}
				/>
				<mesh
					name="Cylinder033"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder033.geometry}
					material={materials["Liquide.001"]}
					position={[0.388, 0.724, 1.17]}
					scale={1.015}
				/>
				<group name="Potion004" position={[0.371, 0.725, 1.072]} scale={1.1}>
					<mesh
						name="Cylinder017"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder017.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder017_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder017_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<mesh
					name="Cylinder035"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder035.geometry}
					material={materials["Liquide.001"]}
					position={[0.371, 0.724, 1.072]}
					scale={1.015}
				/>
				<group name="Potion003" position={[0.407, 0.725, 0.99]} scale={1.1}>
					<mesh
						name="Cylinder029"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder029.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder029_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder029_1.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<mesh
					name="Cylinder037"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder037.geometry}
					material={materials["Liquide.001"]}
					position={[0.407, 0.724, 0.99]}
					scale={1.015}
				/>
				<mesh
					name="Cylinder015"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder015.geometry}
					material={materials.Liquide}
					position={[0.39, 0.355, 1.56]}
					scale={0.043}
				/>
				<mesh
					name="Cylinder016"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder016.geometry}
					material={materials["Liquide.001"]}
					position={[0.41, 0.715, 1.441]}
					scale={0.041}
				/>
				<mesh
					name="Cylinder038"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder038.geometry}
					material={materials["Liquide.001"]}
					position={[0.36, 0.72, 1.34]}
					scale={[0.04, 0.045, 0.04]}
				/>
				<mesh
					name="Cylinder039"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder039.geometry}
					material={materials["Liquide.001"]}
					position={[0.37, 0.706, 1.53]}
					scale={0.032}
				/>
				<mesh
					name="Cylinder040"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder040.geometry}
					material={materials["Liquide.001"]}
					position={[0.42, 0.706, 1.6]}
					scale={0.032}
				/>
				<mesh
					name="Cylinder041"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder041.geometry}
					material={materials["Liquide.001"]}
					position={[0.405, 0.723, 1.28]}
					scale={[1.084, 0.576, 1.084]}
				/>
				<mesh
					name="Sphere008"
					castShadow
					receiveShadow
					geometry={nodes.Sphere008.geometry}
					material={materials["Liquide.001"]}
					position={[0.27, 0.419, 1.04]}
					scale={0.04}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('models/Laboratory_Room.glb');
