/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useContext, useEffect, useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';

import Enigma from '../enigmas/Enigma';
import useInteractiveObject from '../../../hooks/useInteractiveObject';
import { SocketContext } from '../../../contexts/SocketContext';
import { ClientToServer } from '../../../data/socketMessages';
import BasicDisplayTemplate from '../enigmas/BasicEnigmaDisplay';
import InformationPopup from '../informations/InformationPopup';
import EnigmaCoffreDisplay from '../enigmas/EnigmaCoffreDisplay';
import EnigmaWithSlidersDisplay from '../enigmas/EnigmaSliderDisplay';

export default function ReactorRoom(props) {
	const socket = useContext(SocketContext);

	useEffect(() => {
		socket.emit(ClientToServer.RoomLoaded);
	});

	const { nodes, materials } = useGLTF("models/Reactor_Room.glb");

	const PorteInt = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
			forceExit,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Cube019"
				castShadow
				receiveShadow
				geometry={nodes.Cube019.geometry}
				material={materials["Metal.001"]}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0xffcc00} />}
				{clicked && (
					<InformationPopup
						title="Plus rien ne marche !"
						information="Vous étes le nouveau stagiaire de la station de recherche énergétique. 
						Le réacteur c'est emballer et pris de panique vous avez appuyé sur tous les boutons. 
						Par miracle vous l'avez éteint mais il n'y a plus d'électricité. Le réacteur et l'ordinateur ont une batterie de secours qui ne tiendra pas longtemps. 
						Dépêchez-vous de réactiver le réacteur pour ouvrir la porte. Il doit bien avoir des indications sur l'ordinateur."
						closePopup={forceExit}
					/>
				)}
			</mesh>
		);
	};

	const FeuilleInt = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
			forceExit,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Feuilles"
				castShadow
				receiveShadow
				geometry={nodes.Feuilles.geometry}
				material={nodes.Feuilles.material}
				position={[0.25, 1.031, -1.28]}
				rotation={[Math.PI / 2, 0, 1.222]}
				scale={0.231}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0xffcc00} />}
				{clicked && (
					<InformationPopup
						title="Commande Ordinateur"
						information="IP : affiche l'adresse de l'ordinateur / Info -R : Documentation du reacteur"
						closePopup={forceExit}
					/>
				)}
			</mesh>
		);
	};

	const PoubelleInt = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
			forceExit,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Cylinder"
				castShadow
				receiveShadow
				geometry={nodes.Cylinder.geometry}
				material={materials["Metal.001"]}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0xffcc00} />}
				{clicked && (
					<InformationPopup
						title="Tient encore des papier !"
						information="Sur un des papier il y a écrit : 'Pense bete, code coffre : Décomposer la première valeur de l'addresse de l'ordinateur en facteur de nombre premier. (a = x * y * z² => xyzz)'"
						closePopup={forceExit}
					/>
				)}
			</mesh>
		);
	};

	const PosterInt = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
			forceExit,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Poster"
				castShadow
				receiveShadow
				geometry={nodes.Poster.geometry}
				material={nodes.Poster.material}
				position={[1.15, 2.331, -1.999]}
				rotation={[-Math.PI, 0, Math.PI / 2]}
				scale={0.503}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0xffcc00} />}
				{clicked && (
					<InformationPopup
						title="Ca fait un peux de déco."
						information="Ça peut vous aider à chercher l'atome pour le réacteur."
						image="https://i.pinimg.com/originals/5a/72/b7/5a72b79c8f66fca9b3635bc457c3813b.png"
						closePopup={forceExit}
					/>
				)}
			</mesh>
		);
	};

	const CoffreInt = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
			forceExit,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Cube016"
				castShadow
				receiveShadow
				geometry={nodes.Cube016.geometry}
				material={materials["Plastic.001"]}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0xffcc00} />}
				{clicked && (
					<Enigma
						enigmaId={0}
						enigmaDisplayTemplate={(data, hint, handleSubmitAnswer, handleAskHint) => (
							<EnigmaCoffreDisplay
								handleSubmitAnswer={handleSubmitAnswer}
								title="Impossible de forcer le coffre !"
								description="Si il y a autant de sécurité c'est qu'il doit y avoir quelque chose d'important dedans."
								image={data.image}
								hint={hint}
								handleAskHint={handleAskHint}
							/>
						)}
						closeEnigma={forceExit}
					/>
				)}
			</mesh>
		);
	};

	const ConsoleInt = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
			forceExit,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Cylinder005"
				castShadow
				receiveShadow
				geometry={nodes.Cylinder005.geometry}
				material={materials["Plastic.001"]}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0xffcc00} />}
				{clicked && (
					<Enigma
						enigmaId={0}
						enigmaDisplayTemplate={(data, hint, handleSubmitAnswer, handleAskHint) => (
							<EnigmaWithSlidersDisplay
								handleSubmitAnswer={handleSubmitAnswer}
								titreSlider='Volume H2O'
								title="Console"
								description="Il faut trouver le bon code pour réactiver le réacteur."
								image={data.image}
								hint={hint}
								handleAskHint={handleAskHint}
							/>
						)}
						closeEnigma={forceExit}
					/>
				)}
			</mesh>
		);
	};

	const CoreInt = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
			forceExit,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Icosphere"
				castShadow
				receiveShadow
				geometry={nodes.Icosphere.geometry}
				material={materials["Metal.001"]}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0xffcc00} />}
				{clicked && (
					<Enigma
						enigmaId={0}
						enigmaDisplayTemplate={(data, hint, handleSubmitAnswer, handleAskHint) => (
							<BasicDisplayTemplate
								handleSubmitAnswer={handleSubmitAnswer}
								title="Alors peut-être que..."
								description="Mettre le bon atome dans le réacteur."
								image={data.image}
								hint={hint}
								handleAskHint={handleAskHint}
							/>
						)}
						closeEnigma={forceExit}
					/>
				)}
			</mesh>
		);
	};

	return (
		<group {...props} dispose={null}>
			<group name="Scene">
				<mesh
					name="Room001"
					castShadow
					receiveShadow
					geometry={nodes.Room001.geometry}
					material={materials.Room}
					position={[0, 2, 0]}
					scale={2}
				/>
				<mesh
					name="Bureau"
					castShadow
					receiveShadow
					geometry={nodes.Bureau.geometry}
					material={materials["Wood.002"]}
					position={[1, 1, -1.5]}
					scale={[1, 0.03, 0.5]}
				/>
				<group name="Ordi" position={[1.5, 1.41, -1.7]} scale={0.28}>
					<mesh
						name="Cube004"
						castShadow
						receiveShadow
						geometry={nodes.Cube004.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Cube004_1"
						castShadow
						receiveShadow
						geometry={nodes.Cube004_1.geometry}
						material={materials.Screen}
					/>
				</group>
				<group name="Clavier" position={[1.5, 1.04, -1.21]}>
					<mesh
						name="Cube005"
						castShadow
						receiveShadow
						geometry={nodes.Cube005.geometry}
						material={materials.Room}
					/>
					<mesh
						name="Cube005_1"
						castShadow
						receiveShadow
						geometry={nodes.Cube005_1.geometry}
						material={materials["Plastic.001"]}
					/>
				</group>
				<mesh
					name="Cube014"
					castShadow
					receiveShadow
					geometry={nodes.Cube014.geometry}
					material={materials["Metal.001"]}
					position={[-0.18, 0.4, -1.59]}
					rotation={[0, -1.571, 0]}
				/>
				<group name="Poubelle" position={[0.5, 0.2, -1]} scale={0.2}>
					{/*
					<mesh
						name="Cylinder"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder.geometry}
						material={materials["Metal.001"]}
					/>
					*/}
					<PoubelleInt />
					<mesh
						name="Cylinder_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder_1.geometry}
						material={materials["Metal_Orange.002"]}
					/>
				</group>
				<group name="Coffre" position={[1.3, 0.3, 1.6]}>
					{/*
					<mesh
						name="Cube016"
						castShadow
						receiveShadow
						geometry={nodes.Cube016.geometry}
						material={materials["Plastic.001"]}
					/>
					*/}
					<CoffreInt />
					<mesh
						name="Cube016_1"
						castShadow
						receiveShadow
						geometry={nodes.Cube016_1.geometry}
						material={materials["Metal_Orange.002"]}
					/>
				</group>
				<mesh
					name="Chaise"
					castShadow
					receiveShadow
					geometry={nodes.Chaise.geometry}
					material={materials["Wood.002"]}
					position={[1.3, 0.6, -0.2]}
					rotation={[0, Math.PI / 9, 0]}
					scale={[0.28, 0.028, 0.28]}
				/>
				<mesh
					name="Lampe"
					castShadow
					receiveShadow
					geometry={nodes.Lampe.geometry}
					material={materials["Metal.001"]}
					position={[0.39, 1.046, -1.7]}
					rotation={[Math.PI, -0.96, Math.PI]}
					scale={[-0.16, -0.016, -0.16]}
				>
					<mesh
						name="Cube017"
						castShadow
						receiveShadow
						geometry={nodes.Cube017.geometry}
						material={materials["Wire.001"]}
						position={[-0.512, -0.875, 0.358]}
						rotation={[-Math.PI, 0.96, -Math.PI]}
						scale={[-0.125, -0.5, -0.125]}
					/>
					<mesh
						name="Sphere"
						castShadow
						receiveShadow
						geometry={nodes.Sphere.geometry}
						material={materials.Nrj}
						position={[0, -24, 1.55]}
						rotation={[-Math.PI, 0, -Math.PI]}
						scale={[-0.27, -2.7, -0.27]}
					/>
				</mesh>
				<group name="Porte" position={[-1, 1.4, 1.96]}>
					{/*
						<mesh
						name="Cube019"
						castShadow
						receiveShadow
						geometry={nodes.Cube019.geometry}
						material={materials["Metal.001"]}
					/>
					*/}
					<PorteInt />
					<mesh
						name="Cube019_1"
						castShadow
						receiveShadow
						geometry={nodes.Cube019_1.geometry}
						material={materials["Metal_Orange.002"]}
					/>
				</group>
				<mesh
					name="Blue_Wire001"
					castShadow
					receiveShadow
					geometry={nodes.Blue_Wire001.geometry}
					material={materials["Wire.002"]}
					position={[0, 2, 0]}
					scale={2}
				/>
				<mesh
					name="Red_Wire001"
					castShadow
					receiveShadow
					geometry={nodes.Red_Wire001.geometry}
					material={materials["Wire.001"]}
					position={[0, 2, 0]}
					scale={2}
				/>
				<mesh
					name="Cube021"
					castShadow
					receiveShadow
					geometry={nodes.Cube021.geometry}
					material={materials["Plastic.001"]}
					position={[0, 2, 0]}
					scale={2}
				/>
				{/*
				<mesh
					name="Feuilles"
					castShadow
					receiveShadow
					geometry={nodes.Feuilles.geometry}
					material={nodes.Feuilles.material}
					position={[0.25, 1.031, -1.28]}
					rotation={[Math.PI / 2, 0, 1.222]}
					scale={0.231}
				/>
				*/}
				<FeuilleInt />
				{/*
				<mesh
					name="Poster"
					castShadow
					receiveShadow
					geometry={nodes.Poster.geometry}
					material={nodes.Poster.material}
					position={[1.15, 2.331, -1.999]}
					rotation={[-Math.PI, 0, Math.PI / 2]}
					scale={0.503}
				/>
				*/}
				<PosterInt />
				<group name="Tableau" position={[2, 2.092, 0.5]}>
					<mesh
						name="Cube023_1"
						castShadow
						receiveShadow
						geometry={nodes.Cube023_1.geometry}
						material={materials["Plastic.001"]}
					/>
					<mesh
						name="Cube023_2"
						castShadow
						receiveShadow
						geometry={nodes.Cube023_2.geometry}
						material={materials["Wood.002"]}
					/>
				</group>
				<mesh
					name="Papiers_Poubelle"
					castShadow
					receiveShadow
					geometry={nodes.Papiers_Poubelle.geometry}
					material={nodes.Papiers_Poubelle.material}
					position={[0.61, 0.06, -1.04]}
					scale={0.06}
				/>
				<mesh
					name="Room002"
					castShadow
					receiveShadow
					geometry={nodes.Room002.geometry}
					material={materials.Room}
					position={[-1, 5, -7.8]}
					scale={[4, 5, 4]}
				/>
				<mesh
					name="Cylinder004"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder004.geometry}
					material={materials["Wood.002"]}
					position={[-1, 5, -7.8]}
					scale={[4, 5, 4]}
				/>
				<mesh
					name="Blue_Wire002"
					castShadow
					receiveShadow
					geometry={nodes.Blue_Wire002.geometry}
					material={materials["Wire.002"]}
					position={[-1, 5, -7.8]}
					scale={[4, 5, 4]}
				/>
				<group
					name="Console"
					position={[-1, 0.4, -9.6]}
					scale={[1.79, 0.4, 1.79]}
				>
					{/*
					<mesh
						name="Cylinder005"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder005.geometry}
						material={materials["Plastic.001"]}
					/>
					*/}
					<ConsoleInt />
					<mesh
						name="Cylinder005_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder005_1.geometry}
						material={materials["Wire.002"]}
					/>
					<mesh
						name="Cylinder005_2"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder005_2.geometry}
						material={materials.Screen}
					/>
					<mesh
						name="Cylinder005_3"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder005_3.geometry}
						material={materials.Nrj}
					/>
				</group>
				<group name="Reactor_Core" position={[-1, 1.9, -10.1]} scale={1.04}>
					{/*
					<mesh
						name="Icosphere"
						castShadow
						receiveShadow
						geometry={nodes.Icosphere.geometry}
						material={materials["Metal.001"]}
					/>
					*/}
					<CoreInt />
					<mesh
						name="Icosphere_1"
						castShadow
						receiveShadow
						geometry={nodes.Icosphere_1.geometry}
						material={materials.Nrj}
					/>
				</group>
				<group name="Reactor_Support" position={[-1, 1.9, -10.1]} scale={1.3}>
					<mesh
						name="Icosphere001"
						castShadow
						receiveShadow
						geometry={nodes.Icosphere001.geometry}
						material={materials["Metal.001"]}
					/>
					<mesh
						name="Icosphere001_1"
						castShadow
						receiveShadow
						geometry={nodes.Icosphere001_1.geometry}
						material={materials["Metal.002"]}
					/>
					<mesh
						name="Icosphere001_2"
						castShadow
						receiveShadow
						geometry={nodes.Icosphere001_2.geometry}
						material={materials.Nrj}
					/>
				</group>
				<mesh
					name="Red_Wire002"
					castShadow
					receiveShadow
					geometry={nodes.Red_Wire002.geometry}
					material={materials["Wire.001"]}
					position={[-1, 5, -7.8]}
					scale={[4, 5, 4]}
				/>
				<group
					name="Cuve002"
					position={[2.3, 0.5, -7.7]}
					scale={[0.42, 0.5, 0.42]}
				>
					<mesh
						name="Cylinder008"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder008.geometry}
						material={materials["Metal.002"]}
					/>
					<mesh
						name="Cylinder008_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder008_1.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder008_2"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder008_2.geometry}
						material={materials["Metal_Orange.002"]}
					/>
				</group>
				<mesh
					name="Cylinder009"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder009.geometry}
					material={materials["Plastic.001"]}
					position={[-1, 5, -7.8]}
					scale={[4, 5, 4]}
				/>
				<group
					name="Cuve003"
					position={[2, 0.5, -6.6]}
					scale={[0.42, 0.5, 0.42]}
				>
					<mesh
						name="Cylinder009_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder009_1.geometry}
						material={materials["Metal.002"]}
					/>
					<mesh
						name="Cylinder009_2"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder009_2.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder009_3"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder009_3.geometry}
						material={materials["Metal_Orange.002"]}
					/>
				</group>
				<group
					name="Cuve001"
					position={[1.4, 0.5, -5.6]}
					scale={[0.42, 0.5, 0.42]}
				>
					<mesh
						name="Cylinder010"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder010.geometry}
						material={materials["Metal.002"]}
					/>
					<mesh
						name="Cylinder010_1"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder010_1.geometry}
						material={materials["Glass.001"]}
					/>
					<mesh
						name="Cylinder010_2"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder010_2.geometry}
						material={materials["Metal_Orange.002"]}
					/>
				</group>
				<mesh
					name="BezierCurve005"
					castShadow
					receiveShadow
					geometry={nodes.BezierCurve005.geometry}
					material={materials["Plastic.001"]}
					position={[-1, 0, -7.8]}
				/>
				<mesh
					name="BezierCurve006"
					castShadow
					receiveShadow
					geometry={nodes.BezierCurve006.geometry}
					material={materials["Plastic.001"]}
					position={[-1, 0, -7.8]}
				/>
				<mesh
					name="BezierCurve007"
					castShadow
					receiveShadow
					geometry={nodes.BezierCurve007.geometry}
					material={materials["Plastic.001"]}
					position={[-1, 0, -7.8]}
				/>
				<mesh
					name="Cylinder012"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder012.geometry}
					material={materials["Wire.002"]}
					position={[2.3, 0.5, -7.7]}
					scale={[0.42, 0.5, 0.42]}
				/>
				<mesh
					name="Cylinder013"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder013.geometry}
					material={materials["Wire.002"]}
					position={[2, 0.5, -6.6]}
					scale={[0.42, 0.5, 0.42]}
				/>
				<mesh
					name="Cylinder014"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder014.geometry}
					material={materials["Wire.002"]}
					position={[1.4, 0.5, -5.6]}
					scale={[0.42, 0.5, 0.42]}
				/>
				<mesh
					name="Cylinder015"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder015.geometry}
					material={materials["Wire.001"]}
					position={[-1.99, 0.704, -7.486]}
					rotation={[0.215, 0, 0]}
					scale={0.06}
				/>
				<mesh
					name="Cylinder016"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder016.geometry}
					material={materials["Wire.001"]}
					position={[-2.3, 0.732, -7.619]}
					rotation={[0, 1.431, 0.209]}
					scale={0.06}
				/>
				<mesh
					name="Cylinder017"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder017.geometry}
					material={materials["Wire.001"]}
					position={[-2.15, 0.716, -7.541]}
					rotation={[-2.922, 0.988, 3.133]}
					scale={0.06}
				/>
				<mesh
					name="Cylinder018"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder018.geometry}
					material={materials["Wire.001"]}
					position={[-1.3, 0.65, -7.17]}
					scale={0.022}
				/>
				<mesh
					name="Cube023"
					castShadow
					receiveShadow
					geometry={nodes.Cube023.geometry}
					material={materials["Metal.001"]}
					position={[-1.23, 0.67, -7.34]}
					rotation={[0, -0.087, 0]}
				/>
				<mesh
					name="Cube024"
					castShadow
					receiveShadow
					geometry={nodes.Cube024.geometry}
					material={materials["Metal.002"]}
					position={[-0.67, 0.641, -7.15]}
					scale={0.6}
				/>
				<mesh
					name="Cylinder019"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder019.geometry}
					material={materials["Metal.002"]}
					position={[-0.75, 0.66, -7.266]}
					rotation={[0.204, 0, 0]}
					scale={0.024}
				>
					<mesh
						name="Cylinder020"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder020.geometry}
						material={materials["Wire.002"]}
						position={[0, 1, 2.8]}
						scale={[0.7, 0.252, 0.7]}
					/>
				</mesh>
				<mesh
					name="Cylinder021"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder021.geometry}
					material={materials["Metal.002"]}
					position={[-0.82, 0.66, -7.266]}
					rotation={[0.204, 0, 0]}
					scale={0.024}
				>
					<mesh
						name="Cylinder022"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder022.geometry}
						material={materials["Wire.002"]}
						position={[0, 0.851, -2.233]}
						scale={[0.7, 0.252, 0.7]}
					/>
				</mesh>
				<mesh
					name="Cylinder023"
					castShadow
					receiveShadow
					geometry={nodes.Cylinder023.geometry}
					material={materials["Metal.002"]}
					position={[-0.89, 0.66, -7.266]}
					rotation={[0.204, 0, 0]}
					scale={0.024}
				>
					<mesh
						name="Cylinder024"
						castShadow
						receiveShadow
						geometry={nodes.Cylinder024.geometry}
						material={materials["Wire.002"]}
						position={[0, 0.891, 1.248]}
						scale={[0.7, 0.252, 0.7]}
					/>
				</mesh>
				<mesh
					name="Plane"
					castShadow
					receiveShadow
					geometry={nodes.Plane.geometry}
					material={materials.Logo}
					position={[-1, 2, 2.011]}
					rotation={[Math.PI / 2, 0, 0]}
					scale={0.51}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("models/Reactor_Room.glb");
