/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useContext, useEffect, useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';

import Enigma from '../enigmas/Enigma';
import useInteractiveObject from '../../../hooks/useInteractiveObject';
import { SocketContext } from '../../../contexts/SocketContext';
import { ClientToServer } from '../../../data/socketMessages';
import BasicDisplayTemplate from '../enigmas/BasicEnigmaDisplay';
import InformationPopup from '../informations/InformationPopup';

export default function Model(props) {
	const socket = useContext(SocketContext);

	useEffect(() => {
		socket.emit(ClientToServer.RoomLoaded);
	});

	const { nodes, materials } = useGLTF("models/Test_Room_Switch.glb");

	return (
		<group {...props} dispose={null}>
			<group name="Scene">
				<mesh
					name="Plane"
					castShadow
					receiveShadow
					geometry={nodes.Plane.geometry}
					material={materials.Florr}
					scale={3}
				/>
				<mesh
					name="Suzanne"
					castShadow
					receiveShadow
					geometry={nodes.Suzanne.geometry}
					material={materials.Monkey}
					position={[0, 0.55, 0]}
					rotation={[-0.72, -0.516, -0.408]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("models/Test_Room_Switch.glb");
