/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useContext, useEffect, useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';

import Enigma from '../enigmas/Enigma';
import useInteractiveObject from '../../../hooks/useInteractiveObject';
import { SocketContext } from '../../../contexts/SocketContext';
import { ClientToServer } from '../../../data/socketMessages';
import BasicDisplayTemplate from '../enigmas/BasicEnigmaDisplay';
import InformationPopup from '../informations/InformationPopup';

export default function Model(props) {
	const socket = useContext(SocketContext);

	useEffect(() => {
		socket.emit(ClientToServer.RoomLoaded);
	});

	const { nodes, materials } = useGLTF("models/Test_Room_Switch.glb");

	const SuzanneEvent = () => {
		const {
			mesh,
			hovered,
			clicked,
			handlePointerOver,
			handlePointerOut,
			handleClick,
			forceExit,
		} = useInteractiveObject();
		// Mettre les paramètres de l'objet qu'on veut modifier dans le hook
		return (
			<mesh
				ref={mesh}
				name="Suzanne"
				castShadow
				receiveShadow
				geometry={nodes.Suzanne.geometry}
				material={materials.Monkey}
				position={[0, 0.55, 0]}
				rotation={[-0.72, -0.516, -0.408]}
				onPointerOver={handlePointerOver}
				onPointerOut={handlePointerOut}
				onClick={handleClick}
			>
				{hovered && <meshBasicMaterial color={0xf0f0ff} />}
				{clicked && (
					<Enigma
						enigmaId={0}
						enigmaDisplayTemplate={(data, handleSubmitAnswer, handleAskHint) => (
							<BasicDisplayTemplate
								title="Salut Gnibo!"
								description="Je suis un singe! La réponse est 1."
								image={data.image}
								handleSubmitAnswer={handleSubmitAnswer}
								handleAskHint={handleAskHint}
							/>
						)}
						closeEnigma={forceExit}
					/>
				)}
			</mesh>
		);
	};


	return (
		<group {...props} dispose={null}>
			<group name="Scene">
				<mesh
					name="Plane"
					castShadow
					receiveShadow
					geometry={nodes.Plane.geometry}
					material={materials.Florr}
					scale={3}
				/>
				{/*<mesh
					name="Suzanne"
					castShadow
					receiveShadow
					geometry={nodes.Suzanne.geometry}
					material={materials.Monkey}
					position={[0, 0.55, 0]}
					rotation={[-0.72, -0.516, -0.408]}
				/>*/}
				<SuzanneEvent />
			</group>
		</group>
	);
}

useGLTF.preload("models/Test_Room_Switch.glb");
