version: '3.8'
services:
  database:
    image: postgres:16.1-alpine
    environment: # Login et mot de passe : 'dev'
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=enigmathique
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # Insert la configuration (création de la base de données)
      - ./database/data:/var/lib/postgresql/data # Sauvegarde les données (tables, etc.)
volumes:
  database:
    driver: local